services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hamstahstudio\TuningToolShop\:
    resource: '../Classes/*'
    public: true
    exclude:
      - '../Classes/Payment/PaymentResult.php'

  Hamstahstudio\TuningToolShop\Payment\PaymentResult:
    public: true
    autowire: false

  Hamstahstudio\TuningToolShop\Dashboard\OrdersWidget:
    public: true
    tags:
      - name: dashboard.widget
        identifier: 'tuning_tool_shop_orders'
        title: 'LLL:EXT:tuning_tool_shop/Resources/Private/Language/locallang.xlf:dashboard.orders.title'
        description: 'LLL:EXT:tuning_tool_shop/Resources/Private/Language/locallang.xlf:dashboard.orders.description'
        iconIdentifier: 'content-widget-table'
        groupNames: 'tuning_tool_shop'
        height: 'medium'
        width: 'medium'

  Hamstahstudio\TuningToolShop\Dashboard\ProductsWidget:
    public: true
    tags:
      - name: dashboard.widget
        identifier: 'tuning_tool_shop_products'
        title: 'LLL:EXT:tuning_tool_shop/Resources/Private/Language/locallang.xlf:dashboard.products.title'
        description: 'LLL:EXT:tuning_tool_shop/Resources/Private/Language/locallang.xlf:dashboard.products.description'
        iconIdentifier: 'content-widget-list'
        groupNames: 'tuning_tool_shop'
        height: 'medium'
        width: 'medium'

  Hamstahstudio\TuningToolShop\Dashboard\InventoryWidget:
    public: true
    tags:
      - name: dashboard.widget
        identifier: 'tuning_tool_shop_inventory'
        title: 'LLL:EXT:tuning_tool_shop/Resources/Private/Language/locallang.xlf:dashboard.inventory.title'
        description: 'LLL:EXT:tuning_tool_shop/Resources/Private/Language/locallang.xlf:dashboard.inventory.description'
        iconIdentifier: 'content-widget-list'
        groupNames: 'tuning_tool_shop'
        height: 'large'
        width: 'medium'
